[tool.poetry]
name = "finflow"
version = "1.0.0"
description = "Personal budget dashboard"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
SQLAlchemy = "^2.0.36"
psycopg2-binary = "^2.9.10"
matplotlib = "^3.9.2"
alembic = "^1.13.1"
python-dotenv = "^1.0.1"
pyside6 = "^6.10.1"
plotly = "^6.5.0"
mplcursors = "^0.7"
seaborn = "^0.13.2"
qtawesome = "^1.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
mypy = "^1.11.0"
ruff = "^0.6.2"
black = "^24.10.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
finflow = "finflow.dashboard:main"